### ISSUE TITLE
real_b2c branch for ADALiOS does not exist.

### ISSUE THREAD

**Issue by nimatra** [AzureADQuickStarts/B2C-NativeClient-iOS#1]
Did you mean B2C-ADAL branch?

I'm also getting a compile error for not finding ADProfileInfo class definition.

**Comment by Jtango18** [comment]
Hi Nimatra,

This tells me you're pulling from the Master branch. If you pull from Skeleton or Complete, you'll see that the pod file contains the correct branch "convergence-dev" to pull down the source from.

Hope this helps.

Cheers

JT

**Comment by derisen** [comment]
Closing as this repo is being archived.
