### ISSUE TITLE
Could not build module ADALiOS while working with swift project. 

### ISSUE THREAD

**Issue by artiy** [AzureADQuickStarts/B2C-NativeClient-iOS#6]
I created a swift project and imported this library through pod. when I import ADALiOS module in a swift file, it gives me error while compiling the project. my pod file is:

```
platform :ios, '8.0'
use_frameworks!

target 'ADTesting' do
pod 'ADALiOS', :git => 'https://github.com/AzureAD/azure-activedirectory-library-for-objc', :branch => ‘convergence-dev’
end
```

error it was showing is: 

![screen shot 2015-11-30 at 4 24 00 pm](https://cloud.githubusercontent.com/assets/5718195/11469780/e8beb244-977e-11e5-98c0-b09ca226c758.png)

**Comment by derisen** [comment]
Closing as this repo is being archived.
