### ISSUE TITLE
Master not building

### ISSUE THREAD

**Issue by matthiasnagel** [AzureADQuickStarts/B2C-NativeClient-iOS#8]
We have errors building master branch due to Xcode 8 requirements in storyboards. Please do not use beta software in production. Skeleton branch and complete branch need updates caused by invalid pod files. Especially current version of https://github.com/AzureAD/azure-activedirectory-library-for-objc is not compatible with these branches.

**Comment by brandwe** [comment]
Can you explain your last statement? What do you mean that the branches aren't compatible? This was a preview release of B2C support that isn't supported by production standards, and so we point to a branch that isn't the default branch for ADAL iOS. That may be where the confusion is.

**Comment by brandwe** [comment]
I have reverted back to Xcode 7 in the sample. Please validate that you can now build @matthiasnagel. It works on my machine in Xcode 7.

**Comment by matthiasnagel** [comment]
Thanks for your quick reply. Now it's working :-)
You should better set version numbers in the pod file for 'ADALiOS' or push the dependency into repo. If you checkout Skeleton branch and do pod update, you'll see that there are changes in the lib which need to be fixed in Complete branch. Property 'accessToken' has changed for instance.

**Comment by derisen** [comment]
Closing as this repo is being archived.
